## Comparing Arrays

In [2]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([2, 2, 4, 4])

print(a == b)
print(a < b)

[False  True False  True]
[ True False  True False]


## Using Logical Functions

In [4]:
a = np.array([True, False, True, False])
b = np.array([True, True, False, False])

print(np.logical_or(a, b))
print(np.logical_and(a, b))
print(np.logical_not(a))
print(np.logical_xor(a, b))

[ True  True  True False]
[ True False False False]
[False  True False  True]
[False  True  True False]


## Subtraction with matrices

In [6]:
A = np.array([[1, 1], [1, 0]])
B = np.array([[1, 0], [0, 1]])
C = A - B

print(C)

[[ 0  1]
 [ 1 -1]]


## Matrix vector multiplication

In [11]:
a = [sum([4*3, 5*-2]),
sum([2*3, 4*-2]),
sum([3*3, 3*-2])]
print (a)

[2, -2, 3]


## Transposing a matrix

In [12]:
A = np.array([[1, 2, 3], [2, 3, 5], [7, 11, 13]])
print(A.transpose())

[[ 1  2  7]
 [ 2  3 11]
 [ 3  5 13]]


## Inverting a matrix

In [13]:
print(np.linalg.inv(A))

[[-3.2  1.4  0.2]
 [ 1.8 -1.6  0.2]
 [ 0.2  0.6 -0.2]]


## Using ndarray to create a vector

In [14]:
import numpy as np
y = np.array([44,21,37])
print (y)
print (y.shape)

[44 21 37]
(3,)


## Creating a matrix using a single list

In [15]:
X = np.array([1.1, 1, 545, 1, 4.6, 0, 345, 2,
              7.2, 1, 754, 3]).reshape(3,4)
print (X)

[[  1.1   1.  545.    1. ]
 [  4.6   0.  345.    2. ]
 [  7.2   1.  754.    3. ]]
